# Generated by Django 3.0.4 on 2020-11-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201117_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('phone', models.IntegerField(max_length=10, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
