# Generated by Django 3.0.4 on 2021-03-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201123_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_phone', models.CharField(max_length=10)),
                ('your_email', models.EmailField(max_length=200)),
                ('your_service', models.CharField(max_length=100)),
                ('your_date', models.DateField()),
            ],
        ),
    ]
