# Generated by Django 3.0.4 on 2021-03-22 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='your_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service'),
        ),
    ]
