# Generated by Django 3.0.4 on 2021-03-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210322_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='your_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Service'),
        ),
    ]
